name       : pixiewps 
version    : "1.4.2"
release    : 1
source     :
  - git|https://github.com/wiire-a/pixiewps : v1.4.2 
license    :
  - GPL3
component  :
  - security
summary    :
  - Pixiewps is a tool written in C used to bruteforce offline the WPS PIN exploiting the low or non-existing entropy of some software implementations
description: |
  Pixiewps is a tool written in C used to bruteforce offline the WPS PIN exploiting the low or non-existing entropy of some software implementations
networking : true
build      : |
  %make
install    : |
  %make_install
